---
title: "Dataset Symmetry Add to Existing"
author: "Corne Oosthuizen - OSTAND005"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Add Symmetries to Existing datasets

```{r setup-1}
source("utils.R")

dataset.list <- dataset.stats

for (i in 1:nrow(dataset.list)) {
  df.name <- dataset.list[i, 1]
  df.data <- readDF(paste('data/', df.name, '.csv', sep=""))
  assign(df.name, df.data) 
}

rm(df.name)
rm(df.data)
rm(i)

```

## Add Symmetry

```{r}
dataset.list <- subset(subset(dataset.stats, pixels != 0), sym == 0)
#dataset.list <- dataset.list[12,]

dataset.empty <- getEmptyStat()

for(i in 1:nrow(dataset.list)) {

    df <- dataset.list[i,]
  
  print(df$name)
  
  df.src  <- eval(parse(text = df$name))
  df.from <- eval(parse(text = paste(df$name, "_sym", sep="")))
  
  startTime <- Sys.time()
  
  new.df <- cbind(df.src, df.from[,-1])
  
  endTime <- Sys.time()
  runTime <- as.numeric(difftime(endTime, startTime, units = "secs"))
  
  filename <- paste(df$name, '_symAdd', sep="")
  
  write.csv(new.df, file = paste('data/', filename ,'.csv', sep =''))
  saveRDS(new.df, file = paste('data/', filename ,'.rds', sep =''))
  
  dataset.empty <- rbind(dataset.empty, returnStat(name = filename, type = df$type, pixels = df$pixels, 
                                       sym = 1, # the one we are changing
                                       sk = df$sk,
                                       obs = dim(new.df)[1], var = dim(new.df)[2], 
                                       time_s = runTime,
                                       size_b = object.size(new.df)))
}

dataset.empty <- as.data.frame(dataset.empty)

write.csv(dataset.empty, file = 'data/dataset_creation_symAdd.csv')

dataset.empty
```