---
title: "Untitled"
author: "Corné Oosthuizen - OSTAND005"
date: "22 June 2017"
output: html_document
---

sadsd

```{r setup-1}
source("utils.R")

dataset.list <- subset(subset(dataset.stats, pixels != 0), sym == 0)

for (i in 1:nrow(dataset.list)) {
  df.name <- dataset.list[i, 1]
  df.data <- readDF(paste('data/', df.name, '.csv', sep=""))
  assign(df.name, df.data) 
}

rm(df.name)
rm(df.data)
rm(i)

```

## Symmetry

```{r symmetry}

calcVerticalSymmetry <- function(data, rowNumber, size) {
    digit <- matrix(as.numeric(data[rowNumber, -1]), nrow = size)
    #digit <- digit[, nrow(digit):1]  # reverse matrix rows (flip images upside right)
    
    rowSumDiffs <- rep(0, size)
    for (i in 1:size) {                     # loop through each row
        hDiffs <- 0
        for (j in 1:(ncol(digit)/2)) {    # loop through half of the columns
            hDiffs = hDiffs + 1 / (abs(digit[i, j] - digit[i, ncol(digit) - j + 1]) + 1)
        }
        rowSumDiffs[i] <- hDiffs
    }
    return(rowSumDiffs)  # summarize each row's 'symmetry'
}

calcHorizontalSymmetry <- function(data, rowNumber, size) {
    digit <- matrix(as.numeric(data[rowNumber, -1]), nrow = size)
    #digit <- digit[, nrow(digit):1]  # reverse matrix rows (flip images upside right)
    
    colSumDiffs <- rep(0, size)
    for (j in 1:size) {                     # loop through each column
        vDiffs <- 0
        for (i in 1:(nrow(digit)/2)) {    # loop through half of the rows
            vDiffs = vDiffs + 1 / (abs(digit[i, j] - digit[nrow(digit) - i + 1, j]) + 1)
        }
        colSumDiffs[j] <- vDiffs
    }
    return(colSumDiffs)  # summarize each cols' 'symmetry'
}

createDataSet.symmetries <- function(source, addToDF = TRUE) {
  
  source.df <- eval(parse(text = source$name))
  
  startTime <- proc.time()
  
    l <- sqrt(length(source.df)-1)
    
    vsDF <- data.frame(matrix(ncol = l, nrow = nrow(source.df)))
    hsDF <- data.frame(matrix(ncol = l, nrow = nrow(source.df)))
    
    for (i in 1:nrow(source.df)) {
        vsDF[i, ] <- calcVerticalSymmetry(source.df, i, l)
        hsDF[i, ] <- calcHorizontalSymmetry(source.df, i, l)
    }
    
    names(vsDF) <- paste0('vSym', 1:l)
    names(hsDF) <- paste0('hSym', 1:l)
    
    new.df <- cbind(source.df$label, vsDF, hsDF)
    names(new.df) <- c('label', names(vsDF), names(hsDF))
      
    if (addToDF) {
      new.df <- cbind(source.df, vsDF, hsDF)
      names(new.df) <- c(names(source.df), names(vsDF), names(hsDF))
    }
    
  endTime <- proc.time()
  runTime <- endTime - startTime
  
  # filename to store new dataset in
  x <- '_sym'
  l <- 0
  if (addToDF) {
    x <- '_addsym'
    l <- sqrt(length(source.df)-1)
  }
  filename <- paste(source$name, x, sep="")
  
  # write out the new dataset
  write.csv(new.df, file = paste('data/', filename ,'.csv', sep =''))
  
  # add it's details for comparison
  return (returnStat(name = filename, type = source$type, 
                     pixels = l, 
                     sk = source$sk,
                     sym = 1, # the one we are changing
                     obs = dim(new.df)[1], 
                     var = dim(new.df)[2], 
                     time_s = runTime[3], 
                     size_b = object.size(new.df)))
}
```

```{r}
dataset.empty <- getEmptyStat()

for(i in 1:nrow(dataset.list)) {
  #dataset.empty <- rbind(dataset.empty, createDataSet.symmetries(dataset.stats[i,], T))
  dataset.empty <- rbind(dataset.empty, createDataSet.symmetries(dataset.list[i,], F))
}

dataset.empty <- as.data.frame(dataset.empty)
a <- rbind(dataset.stats, dataset.empty)
print(a)

write.csv(a, file = 'data/dataset_creation.csv')
```


```{r}
write.csv(dataset.stats, file = 'data/dataset_creation.csv')
dataset.stats
```
