---
title: "Deep Learning h20"
output: html_notebook
---
```{r}
#install.packages("h2o")

## Load all packages first
suppressMessages(library(h2o))
suppressMessages(library(caret))
suppressMessages(library(mlbench))
suppressMessages(library(ggplot2))

suppressMessages(library(mmand))
suppressMessages(library(PET))

```


```{r readin}

FILE.TRAIN <- "../mnist_data/mnist_train.csv"
FILE.TEST <- "../mnist_data/mnist_test.csv"

train.raw <- read.table(FILE.TRAIN, header = T, dec = ".", sep =",")
test.raw <- read.table(FILE.TEST, header = T, dec = ".", sep =",")

myset <- c(0,2,4,6,7)

train <- subset(train.raw, label == myset)
test <- subset(test.raw, label == myset)

#head(train[1:10])
```

```{r}

rotate <- function(m) { t(apply(m, 1, rev)) }
rotate2 <- function(m) { t(apply(m, 2, rev)) }

t1 <- scaleImage( rotate(matrix(unlist(train[1,-1]), nrow = 28)) )

image(t1, col = gray((128-(0:128))/128), xaxt='n', yaxt='n', asp=1)

```

```{r}
k <- shapeKernel(c(3,3), type="box")

t2 <- scaleImage( rotate(rotate2(matrix(unlist(train[1,-1]), ncol = 28))) )

display(t2)
display(skeletonise(medianFilter(t2, k), k, method="lantuejoul"), col="red", add=TRUE)
```


```{r h2o-cluster, warning=F}
#library(DEEPR)

## start a local h2o cluster
localH2O = h2o.init(max_mem_size = '6g', # use 6GB of RAM of *GB available
                    nthreads = 6) #-1) # use all CPUs (8 on my personal computer :3)
```


```{r}

## MNIST data as H2O
train[,1] = as.factor(train[,1]) # convert digit labels to factor for classification
train_h2o = as.h2o(train)
test_h2o = as.h2o(test)
```

```{r train, message=F, warning=F}

## set timer
s <- proc.time()

## train model
model =
  h2o.deeplearning(x = 2:785,  # column numbers for predictors
                   y = 1,   # column number for label
                   training_frame = train_h2o, # data in H2O format
                   activation = "RectifierWithDropout", # algorithm
                   input_dropout_ratio = 0.2, # % of inputs dropout
                   hidden_dropout_ratios = c(0.5,0.5), # % for nodes dropout
                   balance_classes = TRUE, 
                   hidden = c(100, 100), # two layers of 100 nodes
                   #momentum_stable = 0.99,
                   nesterov_accelerated_gradient = T, # use it for speed,
                   ignore_const_cols = F, # Dropping constant columns
                   epochs = 15) # no. of epochs

```

Dropping constant columns: [pix28_3, pix28_2, pix28_4, pix2_27, pix2_26, pix1_17, pix24_1, pix2_28, pix1_19, pix26_1, pix28_26, pix1_18, pix24_2, pix28_27, pix28_1, pix26_2, pix28_25, pix25_28, pix1_11, pix1_10, pix2_25, pix1_12, pix18_1, pix1_26, pix1_25, pix1_28, pix1_27, pix1_9, pix1_20, pix28_28, pix1_6, pix1_22, pix1_5, pix1_21, pix5_1, pix24_28, pix1_8, pix1_24, pix1_7, pix1_23, pix7_1, pix1_2, pix1_1, pix1_4, pix3_2, pix1_3, pix3_1, pix27_3, pix21_1, pix4_28, pix25_2, pix25_1, pix27_2, pix27_1, pix27_27, pix27_28, pix3_27, pix3_28, pix26_28, pix6_1, pix2_4, pix4_2, pix6_2, pix2_1, pix2_3, pix4_1, pix2_2].


```{r savedata, message=F, warning=F}
## print confusion matrix
#h2o.confusionMatrix(model)

#h2o.confusionMatrix(model)$Error[11]
#1 - h2o.confusionMatrix(model)$Error[11]

proc.time() - s


# now make a prediction
predictionsTrain <- h2o.predict(model, train_h2o)
#predictionsTrain

predictionsTest <- h2o.predict(model, test_h2o)
#predictionsTest

yhatTrain = as.factor(as.matrix(predictionsTrain$predict))
confusionMatrix(yhatTrain, train$label)

yhatTest = as.factor(as.matrix(predictionsTest$predict))
confusionMatrix(yhatTest, test$label)

```
```{r}
a = (yhatTrain == train$label)
b = which(a=="FALSE")
c = train[b,]
d = yhatTrain[b]

par(mfrow=c(4,4),pty='s',mar=c(1,1,1,1),xaxt='n',yaxt='n')

for(i in 1:nrow(c)) {
  #z = rotate(matrix(unlist(c[i, -1]), nrow = 28))
  image(rotate(matrix(unlist(c[i, -1]), nrow = 28)), col = gray((128-(0:128))/128), xaxt='n', yaxt='n', asp=1, main = paste("T: ", c[i, 1]," P:",d[i]))
}

```

```{r}
a = (yhatTest == test$label)
b = which(a=="FALSE")
c = test[b,]
d = yhatTest[b]

par(mfrow=c(4,4),pty='s',mar=c(1,1,1,1),xaxt='n',yaxt='n')

for(i in 1:nrow(c)) {
  #z = rotate(matrix(unlist(c[i, -1]), nrow = 28))
  image(rotate(matrix(unlist(c[i, -1]), nrow = 28)), col = gray((128-(0:128))/128), xaxt='n', yaxt='n', asp=1, main = paste("T: ", c[i, 1]," P:",d[i]))
}

```

```{r}
## shut down virutal H2O cluster
h2o.shutdown(prompt = F)
```