---
title: "MNIST_PCA"
author: "lbslou003"
date: "6/1/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=T, eval=TRUE}
start.time <- Sys.time()
MNIST.df.train = read.csv('./mnist_data/mnist_train.csv')

X.train = MNIST.df.train[MNIST.df.train["label"] == 0 | MNIST.df.train["label"] == 1 | MNIST.df.train["label"] == 3 | MNIST.df.train["label"] == 4 | MNIST.df.train["label"] == 6 , -1]
Y.train = MNIST.df.train[MNIST.df.train["label"] == 0 | MNIST.df.train["label"] == 1 | MNIST.df.train["label"] == 3 | MNIST.df.train["label"] == 4 | MNIST.df.train["label"] == 6 , 1]

Y.train = factor(Y.train, labels=c("0", "1", "3", "4", "6"))
dataset.train = cbind(Y.train, X.train)


MNIST.df.test = read.csv('./mnist_data/mnist_test.csv')

X.test = MNIST.df.test[MNIST.df.test["label"] == 0 | MNIST.df.test["label"] == 1 | MNIST.df.test["label"] == 3 | MNIST.df.test["label"] == 4 | MNIST.df.test["label"] == 6 , -1]
Y.test = MNIST.df.test[MNIST.df.test["label"] == 0 | MNIST.df.test["label"] == 1 | MNIST.df.test["label"] == 3 | MNIST.df.test["label"] == 4 | MNIST.df.test["label"] == 6 , 1]

Y.test = factor(Y.test, labels=c("0", "1", "3", "4", "6"))

dataset.test = cbind(Y.test, X.test)

time.taken <- Sys.time() - start.time;time.taken
```
```{r}
X.train.scaled <- data.frame(lapply(X.train, function(x) scale(x, center = TRUE, scale = TRUE)))
head(X.train.scaled)
```

```{r}

library(class)

N = dim(dataset.train)[1]
N.test = dim(dataset.test)[1]
k= 20

for(k in c(1,10,50,100)){

  #for (N in c(200,500,1000,2000)){
    writeLines("-----------------------------------------")
    writeLines(paste0("Evaluating for k = ",k, ", N = ", N))
    writeLines("-----------------------------------------")
    
    start.time <- Sys.time()
    knn.1 <-  knn(dataset.train[1:N,], dataset.test[1:N.test,], Y.train[1:N], k=1)
    
    
    correct = sum(Y.test[1:N.test] == knn.1)
    all = length(Y.test[1:N.test])
    wrong = all - correct
    
    
    writeLines(paste0("All: ",all, ", Correct: ",correct, ", Wrong: ",wrong, ", Accuracy: ", round(100 * correct/all,2), " %"))
    print(Sys.time() - start.time)
    
  #}
}



```

```{r}
knn.1
100 * sum(Y.test == knn.1)/100  # For knn = 1
```


