---
title: "Create Images for Cluster Analysis and Multdimentional Scaling"
author: "Corne Oosthuizen - OSTAND005"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Cluster Analysis and Multidimentional Scaling

```{r setup-1}
source("utils.R")

dataset.list <- dataset.stats

```


```{r libraries, echo=FALSE, eval=TRUE, warning=FALSE, error=FALSE}
library(cluster)
library(MASS)
library(smacof)
```


```{r set_data, warning=FALSE}

dataset.stats[,2] <- factor(dataset.stats[,2]) # type
dataset.stats[,3] <- factor(dataset.stats[,3]) # pixels
dataset.stats[,4] <- factor(dataset.stats[,4]) # sym
dataset.stats[,5] <- factor(dataset.stats[,5]) # skeleton
dataset.stats[,6] <- factor(dataset.stats[,6]) # pca

tbl <- table(dataset.stats$type, dataset.stats$pixels)
tbl <- cbind(tbl, apply(tbl,1,sum))
tbl <- rbind(tbl, apply(tbl,2,sum))

cat("Type by Pixels\n")
cat("--------------\n")
print(tbl)

df <- dataset.stats[ , !(names(dataset.stats) %in% c('size_b'))]
Dmat <- daisy(df[, -1], metric="gower")
```

```{r pca, warning=FALSE}
if (!require("dendextend")) {
   install.packages("dendextend", dependencies = TRUE)
   library(dendextend)
   }
if (!require("stringr")) {
   install.packages("stringr", dependencies = TRUE)
   library(stringr)
}
if (!require("gplots")) {
   install.packages("gplots", dependencies = TRUE)
   library(gplots)
   }
if (!require("RColorBrewer")) {
   install.packages("RColorBrewer", dependencies = TRUE)
   library(RColorBrewer)
}

out.complete.euc <- hclust(Dmat, method="complete")
out.complete.euc$labels <- dataset.stats[,1]
#plot(out.complete.euc, cex = 0.5)
#abline(h=0.6)
#abline(h=0.5)
#abline(h=0.425)

cut1 <- 0.2
cut2 <- 0.42

dend <- as.dendrogram(out.complete.euc)
dend <- set(dend, "labels_cex", 0.7)

png("img/dendo.png", width = 1024, height = 600)

par(mar = c(2,1,1,4))

dend %>% ladderize %>%  plot(horiz = TRUE, cex.axis=1); 
abline(v = cut, col="#723C2C", lty = 2)
abline(v = cut, col="#723C2C", lty = 2)

dev.off()

lbls <- apply(dataset.stats, 1, function(x) { 
  # Create a summary of an observation
  #  
  #  Train : 28=A 14=B 7=C 0=D
  #  Test  : 28=Z 14=Y 7=X 0=W
  #  000   : Symmmetry Skeleton PCA
  
  st <- switch(x[2],
        train = switch(x[3], '28' = "A", '14' = "B", '7' = "C", '0' = "D"),
        test = switch(x[3], '28' = "Z", '14' = "Y", '7' = "X", '0' = "W"))
  
  return (paste(st, x[4], x[6], x[5], sep="")) 
})

out.Euc <- smacofSym(Dmat, type="ratio")$conf


# CLUSTER PROFILING - cut1

out.complete.cut <- cutree(out.complete.euc, h = cut1)
names (out.complete.cut) <- dataset.stats[,1]

clusvec <- out.complete.cut
colvec <- colorRampPalette(c("#2E62A1", "#7B2A95","#E45E2D"))(n = max(clusvec)) ##4C3430

# create empty plot
png("img/mds_cut1.png", width = 600, height = 600)
plot (out.Euc, type="n", xlab="", ylab="", xaxt="n", yaxt="n", asp=1, main= paste("MDS for Datasets (",cut1,")", sep=""))

for (i in 1:nrow(dataset.stats)) {
  text (out.Euc[i,1], out.Euc[i,2], lbls[i], col=colvec[clusvec[i]], cex=0.75)
}
dev.off()

# CLUSTER PROFILING - cut2

out.complete.cut <- cutree(out.complete.euc, h = cut2)
names (out.complete.cut) <- dataset.stats[,1]

clusvec <- out.complete.cut
colvec <- colorRampPalette(c("#2E62A1", "#E45E2D"))(n = max(clusvec)) ##4C3430

#colvec <- c("#4D4D4D","#5DA5DA","#FAA43A","#60BD68","#F15854","#B276B2")

# create empty plot
png("img/mds_cut2.png", width = 600, height = 600)
plot (out.Euc, type="n", xlab="", ylab="", xaxt="n", yaxt="n", asp=1, main= paste("MDS for Datasets (",cut2,")", sep=""))

for (i in 1:nrow(dataset.stats)) {
  text (out.Euc[i,1], out.Euc[i,2], lbls[i], col=colvec[clusvec[i]], cex=0.75)
}
dev.off()
```