---
title: "R Notebook"
output: html_notebook
---

```{r read-data, echo=FALSE, eval=TRUE}
FILE <- "rec_data.csv"

df.raw <- read.table(FILE, header = T, dec = ".", sep =",")
df.drop <- c("id","date_created", "date_started", "date_completed", "first_step", "last_step")

df <- df.raw[ , !(names(df.raw) %in% df.drop)]
str(df)

sum(complete.cases(df))
```



```{r}

df.edit <- df[df["process_type"] == "uct-process-before-edit",]
df.publish <- df[df["process_type"] == "uct-publish-after-edit",]

boxplot(df.edit$duration)
boxplot(df.publish$duration)

```


```{r}
# returns string w/o leading or trailing whitespace
trim <- function (x) gsub("^\\s+|\\s+$", "", x)

timespan.len <- c(31536000,2592000,604800,86400,3600,60,1)
timespan.st <- list('year','month','week','day','h','m','s')

display_time <- function(d) {
  d <- d/1000
  r <- vector(length=7)
  
  for (i in 1:length(timespan.len)) {
    r[i] = floor(d / timespan.len[i]);
    d <- d - (r[i] * timespan.len[i]);
  }
  
  st <- ""
  for (i in 1:length(r)) {
    
    if (r[i] != 0) {
      st <- paste(st, paste(r[i], timespan.st[i], sep=""), sep =" ")
    }
  }
  
  return (trim(st))
}

message("Number of Processes:")
message("  Process for editing: ", nrow(df.edit))
message("  Publish recording: ", nrow(df.publish))
message("")
message("Mean Time:")
message("  Process for editing: ", display_time(mean(df.edit$duration)))
message("  Publish recording: ", display_time(mean(df.publish$duration)))

```


```{r}

bitrates <- read.table("bitrates.csv", header = T, dec = ".", sep =",")
nrow(bitrates)
names(bitrates)
#head(bitrates)

mod <- lm(size ~ (bitrate/duration), data = bitrates)
summary(mod)
```

```{r}
br <- mean(bitrates$bitrate)

calcbit <- function(duration) {
  2.774e+05 + (duration * -1.223e-02)
}

calcsize <- function(bitrate, duration) {
  (bitrate * 4.285e+02) + (duration * 2.289e+01) -8.152e+07
}

calcsize2 <- function(bitrate, duration) {
  (1.260e-04 * bitrate/duration) + 2.296e+06
}

br
calcbit(3300083)
calcsize(br, 3300083)*8/1024/1024
calcsize2(br, 3300083)*8
calcsize(calcbit(3300083), 3300083)*8/1024/1024
calcsize2(calcbit(3300083), 3300083)*8
504066244/1024/1024

#plot(bitrate~I(size*duration), data=bitrates)
```






asdasdasd